knowledge_base.test.test_context
  TestContext
    test_add_field ...                                                     [OK]
    test_mod_field ...                                                     [OK]
  TestContextManager
    test_clear_test ... creating context, type=user_context_1, paras={'a': 1, 'c': 3, 'b': 2}.
                                                [ERROR]
    test_create_context ... creating context, type=user_context_1, paras={'p2': 2, 'a': 3, 'c': 5, 'p1': 1, 'm': 8, 'n': 9, 'b': 4}.
                                            [ERROR]
    test_destroy_context ... creating context, type=user_context_1, paras={'a': 1, 'c': 3, 'b': 2}.
                                           [ERROR]
    test_get_context ... creating context, type=user_context_1, paras={'p2': 2, 'a': 3, 'c': 5, 'p1': 1, 'm': 8, 'n': 9, 'b': 4, 'y': 7, 'x': 6}.
                                               [ERROR]
    test_load_index_of_context ...                                       [FAIL]
  TestIndex
    test_delete_all_indexes ... 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'p2': 2, 'context_id': 0, 'p1': 1}, (3, 4): {'p2': 4, 'context_id': 2, 'p1': 3}, (2, 3): {'p2': 3, 'context_id': 1, 'p1': 2}})


Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={})

                                           [OK]
    test_get_context ... 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'p2': 2, 'context_id': 0, 'p1': 1}})

                                                  [OK]
    test_insert_index ... 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'a': 1, 'p2': 2, 'p1': 1, 'context_id': 0}})


Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'a': 1, 'p2': 2, 'p1': 1, 'context_id': 0}})


Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'a': 1, 'p2': 2, 'p1': 1, 'context_id': 0}})

                                                 [OK]
    test_update_index ... 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'p2': 2, 'context_id': 0, 'p1': 1}})


Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(10, 2): {'p2': 2, 'context_id': 0, 'p1': 10}})


Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(10, 2): {'p2': 2, 'context_id': 0, 'p1': 10}})

                                                 [OK]
  TestIndexList
    test_get_context ... 
IndexList(
	context_type=user_ctxt_1
	key=[('p1', 'p2'), ('x',), ('a', 'b', 'c')]
	index={('p1', 'p2'): 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'p2': 2, 'context_id': 0, 'p1': 1}})
, ('a', 'b', 'c'): 
Index(
	context_type=user_ctxt_1
	key=('a', 'b', 'c')
	index={})
, ('x',): 
Index(
	context_type=user_ctxt_1
	key=('x',)
	index={})
})

finding context...
finding context...
finding context...
cannot find context by given keys.
                                                  [OK]
    test_insert_index ... inserting index and context...
inserting index to context: ('p1', 'p2')
value of the key in the context: (1, 2)
inserting index to context: ('x',)
value of the key in the context: (6,)
inserting index to context: ('a', 'b', 'c')
value of the key in the context: (3, 4, 5)
inserting context into index ('p1', 'p2')
inserting context into index ('x',)
inserting context into index ('a', 'b', 'c')

IndexList(
	context_type=user_ctxt_1
	key=[('p1', 'p2'), ('x',), ('a', 'b', 'c')]
	index={('p1', 'p2'): 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
, ('a', 'b', 'c'): 
Index(
	context_type=user_ctxt_1
	key=('a', 'b', 'c')
	index={(3, 4, 5): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
, ('x',): 
Index(
	context_type=user_ctxt_1
	key=('x',)
	index={(6,): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
})

finding context...
finding context...
finding context...
inserting index and context...
no matching keys found.

IndexList(
	context_type=user_ctxt_1
	key=[('p1', 'p2'), ('x',), ('a', 'b', 'c')]
	index={('p1', 'p2'): 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
, ('a', 'b', 'c'): 
Index(
	context_type=user_ctxt_1
	key=('a', 'b', 'c')
	index={(3, 4, 5): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
, ('x',): 
Index(
	context_type=user_ctxt_1
	key=('x',)
	index={(6,): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
})

finding context...
cannot find context by given keys.
inserting index and context...
context type mismatch.

IndexList(
	context_type=user_ctxt_1
	key=[('p1', 'p2'), ('x',), ('a', 'b', 'c')]
	index={('p1', 'p2'): 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
, ('a', 'b', 'c'): 
Index(
	context_type=user_ctxt_1
	key=('a', 'b', 'c')
	index={(3, 4, 5): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
, ('x',): 
Index(
	context_type=user_ctxt_1
	key=('x',)
	index={(6,): {'a': 3, 'p2': 2, 'c': 5, 'b': 4, 'context_id': 0, 'x': 6, 'p1': 1}})
})

finding context...
                                                 [OK]
    test_update_index ... inserting index and context...
inserting index to context: ('p1', 'p2')
value of the key in the context: (1, 2)
inserting index to context: ('x',)
context key not exist
value of the key in the context: None
inserting index to context: ('a', 'b', 'c')
context key not exist
value of the key in the context: None
inserting context into index ('p1', 'p2')

IndexList(
	context_type=user_ctxt_1
	key=[('p1', 'p2'), ('x',), ('a', 'b', 'c')]
	index={('p1', 'p2'): 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 2): {'p2': 2, 'context_id': 0, 'p1': 1}})
, ('a', 'b', 'c'): 
Index(
	context_type=user_ctxt_1
	key=('a', 'b', 'c')
	index={})
, ('x',): 
Index(
	context_type=user_ctxt_1
	key=('x',)
	index={})
})


IndexList(
	context_type=user_ctxt_1
	key=[('p1', 'p2'), ('x',), ('a', 'b', 'c')]
	index={('p1', 'p2'): 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 10): {'p2': 10, 'context_id': 0, 'p1': 1}})
, ('a', 'b', 'c'): 
Index(
	context_type=user_ctxt_1
	key=('a', 'b', 'c')
	index={})
, ('x',): 
Index(
	context_type=user_ctxt_1
	key=('x',)
	index={})
})

finding context...

IndexList(
	context_type=user_ctxt_1
	key=[('p1', 'p2'), ('x',), ('a', 'b', 'c')]
	index={('p1', 'p2'): 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 10): {'p2': 10, 'a': 3, 'c': 5, 'p1': 1, 'context_id': 0, 'b': 4}})
, ('a', 'b', 'c'): 
Index(
	context_type=user_ctxt_1
	key=('a', 'b', 'c')
	index={(3, 4, 5): {'p2': 10, 'a': 3, 'c': 5, 'p1': 1, 'context_id': 0, 'b': 4}})
, ('x',): 
Index(
	context_type=user_ctxt_1
	key=('x',)
	index={})
})

finding context...

IndexList(
	context_type=user_ctxt_1
	key=[('p1', 'p2'), ('x',), ('a', 'b', 'c')]
	index={('p1', 'p2'): 
Index(
	context_type=user_ctxt_1
	key=('p1', 'p2')
	index={(1, 10): {'p2': 10, 'a': 3, 'c': 5, 'p1': 1, 'context_id': 0, 'b': 4, 'x': 6}})
, ('a', 'b', 'c'): 
Index(
	context_type=user_ctxt_1
	key=('a', 'b', 'c')
	index={(3, 4, 5): {'p2': 10, 'a': 3, 'c': 5, 'p1': 1, 'context_id': 0, 'b': 4, 'x': 6}})
, ('x',): 
Index(
	context_type=user_ctxt_1
	key=('x',)
	index={(6,): {'p2': 10, 'a': 3, 'c': 5, 'p1': 1, 'context_id': 0, 'b': 4, 'x': 6}})
})

finding context...
                                                 [OK]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "D:\Work\Projects\EPC_Test\knowledge_base\test\test_context.py", line 164, in test_load_index_of_context
    self.assertEqual(len(self.cm._indexes), 7)
  File "C:\Python27\lib\unittest\case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python27\lib\unittest\case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
exceptions.AssertionError: 0 != 7

knowledge_base.test.test_context.TestContextManager.test_load_index_of_context
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "D:\Work\Projects\EPC_Test\knowledge_base\test\test_context.py", line 266, in test_clear_test
    a=1,b=2,c=3)
  File "D:\Work\Projects\EPC_Test\knowledge_base\context.py", line 66, in create_context
    self._indexes[t].insert_index(c)
exceptions.KeyError: 'user_context_1'

knowledge_base.test.test_context.TestContextManager.test_clear_test
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "D:\Work\Projects\EPC_Test\knowledge_base\test\test_context.py", line 171, in test_create_context
    m=8, n=9)
  File "D:\Work\Projects\EPC_Test\knowledge_base\context.py", line 66, in create_context
    self._indexes[t].insert_index(c)
exceptions.KeyError: 'user_context_1'

knowledge_base.test.test_context.TestContextManager.test_create_context
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "D:\Work\Projects\EPC_Test\knowledge_base\test\test_context.py", line 240, in test_destroy_context
    a=1,b=2,c=3)
  File "D:\Work\Projects\EPC_Test\knowledge_base\context.py", line 66, in create_context
    self._indexes[t].insert_index(c)
exceptions.KeyError: 'user_context_1'

knowledge_base.test.test_context.TestContextManager.test_destroy_context
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "D:\Work\Projects\EPC_Test\knowledge_base\test\test_context.py", line 208, in test_get_context
    m=8, n=9)
  File "D:\Work\Projects\EPC_Test\knowledge_base\context.py", line 66, in create_context
    self._indexes[t].insert_index(c)
exceptions.KeyError: 'user_context_1'

knowledge_base.test.test_context.TestContextManager.test_get_context
-------------------------------------------------------------------------------
Ran 14 tests in 0.015s

FAILED (failures=1, errors=4, successes=9)
